name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.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 }}"
        tag_prefix: "v"
        changelog_structure: "**{{messageHeadline}}** {{author}}\n"
